  telegram_coffee_bot:
    build: https://github.com/Eldies/telegram_coffee_bot.git#main
    restart: always
    environment:
      BOT_TOKEN: TOKEN
      MONGODB_DB_NAME: coffee_bot
      MONGODB_CONNECTION_STRING: mongodb://localhost:27017
      GOOGLE_MAPS_API_KEY: KEY
